name    'KyleAnderson-etcd'
version '0.4.0'
source 'https://github.com/solarkennedy/puppet-etcd'
author 'KyleAnderson'
license 'Apache License, Version 2.0'
summary 'A Puppet module to install and configure etcd!'
description 'A Puppet module to install and configure etcd!'
project_page 'https://github.com/solarkennedy/puppet-etcd'
dependency 'puppetlabs/stdlib', '>= 0.1.6'
